Repository candlepin/candlepin, pull requests merged in 2018-02, with the labels that each got.

#1903 Awood/1478549 update hornetq
  buildfile
  common/pom.xml
  server/bin/deploy
  server/pom.xml
  server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java
  server/src/main/java/org/candlepin/audit/EventFilter.java
  server/src/main/java/org/candlepin/audit/EventSinkImpl.java
  server/src/main/java/org/candlepin/audit/EventSource.java
  server/src/main/java/org/candlepin/audit/ListenerWrapper.java
  server/src/main/java/org/candlepin/audit/QueueStatus.java
  server/src/main/java/org/candlepin/config/ConfigProperties.java
  server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
  server/src/main/java/org/candlepin/guice/CandlepinModule.java
  server/src/main/java/org/candlepin/jackson/PoolSerializer.java
  server/src/main/java/org/candlepin/resource/AdminResource.java
  server/src/test/java/org/candlepin/audit/EventSinkImplTest.java
  server/src/test/java/org/candlepin/audit/EventSourceTest.java
  server/src/test/java/org/candlepin/audit/ListenerWrapperTest.java
  server/src/test/java/org/candlepin/config/CandlepinCommonTestConfig.java
  server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
Labels: Ignore Jenkins failures

#1910 Product Certificate DTO
  server/src/main/java/org/candlepin/dto/StandardTranslator.java
  server/src/main/java/org/candlepin/dto/api/v1/ProductCertificateDTO.java
  server/src/main/java/org/candlepin/dto/api/v1/ProductCertificateTranslator.java
  server/src/main/java/org/candlepin/model/ProductCertificate.java
  server/src/main/java/org/candlepin/resource/OwnerProductResource.java
  server/src/main/java/org/candlepin/resource/ProductResource.java
  server/src/test/java/org/candlepin/dto/api/v1/ProductCertificateDTOTest.java
  server/src/test/java/org/candlepin/dto/api/v1/ProductCertificateTranslatorTest.java
  server/src/test/java/org/candlepin/resource/OwnerProductResourceTest.java
  server/src/test/java/org/candlepin/resource/ProductResourceTest.java
Labels: merge after Jenkins

#1922 Pull corrected translations from Zanata.
  common/po/fr.po
  common/po/ja.po
  common/po/ko.po
  common/po/zh_CN.po
Labels: merge after Jenkins

#1921 [M] Add Java 8 to mead packages argument
  server/mead.chain
Labels: ASAP

#1923 Correct incorrect punctuation in user messages.
  common/src/main/java/org/candlepin/common/resteasy/filter/PageRequestFilter.java
  common/src/main/java/org/candlepin/common/validation/CandlepinMessageInterpolator.java
  server/spec/autobind_disabled_for_owner_spec.rb
  server/spec/consumer_resource_dev_spec.rb
  server/spec/derived_product_spec.rb
  server/spec/healing_spec.rb
  server/src/main/java/org/candlepin/controller/Entitler.java
  server/src/main/java/org/candlepin/controller/ManifestManager.java
  server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
  server/src/main/java/org/candlepin/model/ConsumerCurator.java
  server/src/main/java/org/candlepin/model/EntitlementCurator.java
  server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
  server/src/main/java/org/candlepin/policy/js/activationkey/ActivationKeyRules.java
  server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
  server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRulesTranslator.java
  server/src/main/java/org/candlepin/resource/ConsumerResource.java
  server/src/main/java/org/candlepin/resource/ConsumerTypeResource.java
  server/src/main/java/org/candlepin/resource/EntitlementResource.java
  server/src/main/java/org/candlepin/resource/EventResource.java
  server/src/main/java/org/candlepin/resource/HypervisorResource.java
  server/src/main/java/org/candlepin/resource/OwnerProductResource.java
  server/src/main/java/org/candlepin/resource/OwnerResource.java
  server/src/main/java/org/candlepin/resource/PoolResource.java
  server/src/main/java/org/candlepin/resource/ProductResource.java
  server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
  server/src/main/java/org/candlepin/util/ServiceLevelValidator.java
  server/src/test/java/org/candlepin/controller/EntitlerTest.java
  server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
  server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
  server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
Labels: merge after Jenkins
