Repository candlepin/candlepin, pull requests merged in 2023-05, with the labels that each got.

#3995 Fix random unit test failures
  src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
  src/test/java/org/candlepin/test/TestUtil.java
Labels: merge after Jenkins

#3940 CANDLEPIN-522: Move spec test execution outside of container
  containers/cp-test
  containers/test
  jenkins/Jenkinsfile
  jenkins/cleanup.sh
  jenkins/collect_artifacts.sh
  jenkins/spec-tests.sh
Labels: Needs Second Review

#3837 [4.2] Translations update from Fedora Weblate
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/pt_BR.po
  po/uk.po
  po/zh_CN.po
Labels: merge after Jenkins

#4002 [M] CANDLEPIN-580: Fixed various remapping issues during refresh
  src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
  src/main/java/org/candlepin/controller/refresher/builders/ContentNodeBuilder.java
  src/main/java/org/candlepin/controller/refresher/builders/ProductNodeBuilder.java
  src/main/java/org/candlepin/controller/refresher/mappers/AbstractEntityMapper.java
  src/main/java/org/candlepin/controller/refresher/mappers/ContentMapper.java
  src/main/java/org/candlepin/controller/refresher/mappers/EntityMapper.java
  src/main/java/org/candlepin/controller/refresher/mappers/PoolMapper.java
  src/main/java/org/candlepin/controller/refresher/mappers/ProductMapper.java
  src/main/java/org/candlepin/controller/refresher/nodes/AbstractNode.java
  src/main/java/org/candlepin/controller/refresher/nodes/EntityNode.java
  src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
  src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
  src/main/java/org/candlepin/model/ContentCurator.java
  src/main/java/org/candlepin/model/OwnerProductCurator.java
  src/main/java/org/candlepin/model/Product.java
  src/main/java/org/candlepin/model/ProductCurator.java
  src/test/java/org/candlepin/controller/refresher/RefreshWorkerTest.java
  src/test/java/org/candlepin/controller/refresher/builders/ContentNodeBuilderTest.java
  src/test/java/org/candlepin/controller/refresher/builders/ProductNodeBuilderTest.java
  src/test/java/org/candlepin/controller/refresher/mappers/AbstractEntityMapperTest.java
  src/test/java/org/candlepin/controller/refresher/mappers/ContentMapperTest.java
  src/test/java/org/candlepin/controller/refresher/mappers/ProductMapperTest.java
  src/test/java/org/candlepin/controller/refresher/nodes/AbstractNodeTest.java
  src/test/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitorTest.java
  src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
  src/test/java/org/candlepin/model/ContentCuratorTest.java
  src/test/java/org/candlepin/model/ProductCuratorTest.java
  src/test/java/org/candlepin/policy/AutobindRulesTest.java
  src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
  src/test/java/org/candlepin/policy/PoolRulesTest.java
Labels: Needs Second Review

#4012 [M] CANDLEPIN-565: Updated dev environment cert generation script
  bin/deployment/deploy
  bin/deployment/gen_certs.sh
  src/main/java/org/candlepin/auth/SSLAuth.java
Labels: merge after Jenkins

#3997 CANDLEPIN-569: Run liquibase update on startup
  bin/deployment/deploy
  config/candlepin/candlepin.conf.template
  src/main/java/org/candlepin/config/ConfigProperties.java
  src/main/java/org/candlepin/guice/CandlepinContextListener.java
  src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
Labels: Needs Second Review, merge after Jenkins
