Repository candlepin/candlepin, pull requests merged in 2024-11, with the labels that each got.

#4909 [M] CANDLEPIN-938: Updated query space declarations for native SQL queries
  src/main/java/org/candlepin/model/AbstractHibernateCurator.java
  src/main/java/org/candlepin/model/CertificateSerialCurator.java
  src/main/java/org/candlepin/model/ConsumerContentOverrideCurator.java
  src/main/java/org/candlepin/model/ConsumerCurator.java
  src/main/java/org/candlepin/model/ContentCurator.java
  src/main/java/org/candlepin/model/ContentQueryBuilder.java
  src/main/java/org/candlepin/model/EntitlementCurator.java
  src/main/java/org/candlepin/model/EnvironmentCurator.java
  src/main/java/org/candlepin/model/PoolCurator.java
  src/main/java/org/candlepin/model/ProductCurator.java
  src/main/java/org/candlepin/model/ProductQueryBuilder.java
  src/main/java/org/candlepin/model/activationkeys/ActivationKeyCurator.java
  src/main/java/org/candlepin/testext/manifestgen/EntityMapper.java
Labels: Needs Second Review

#4907 [M] CANDLEPIN-945: Handle EntityNotFoundException in ConsumerStore.lookup
  src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
Labels: merge after CI

#4920 [M] CANDLEPIN-938: Registered ObjectMapper as an eager singleton
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/test/java/org/candlepin/TestingModules.java
Labels: merge after CI

#4921 [M] CANDLEPIN-938: Updated KeycloakConfiguration to be a singleton
  src/main/java/org/candlepin/auth/KeycloakConfiguration.java
Labels: merge after CI

#4922 Update Gradle Wrapper from 8.10.2 to 8.11
  gradle/wrapper/gradle-wrapper.properties
Labels: gradle-wrapper

#4929 [M] CANDLEPIN-938: Added caching to the Consumer entity
  src/main/java/org/candlepin/model/Consumer.java
Labels: merge after CI

#4939 [M] CANDLEPIN-954: Relaxed constraint on null values in ConsumerCloudData
  spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java
  spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Request.java
  spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
  spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
  src/main/java/org/candlepin/model/CloudIdentifierFacts.java
  src/main/java/org/candlepin/model/Consumer.java
  src/main/java/org/candlepin/model/ConsumerCloudData.java
  src/main/java/org/candlepin/resource/ConsumerResource.java
  src/main/java/org/candlepin/util/Util.java
  src/test/java/org/candlepin/model/ConsumerCloudDataTest.java
  src/test/java/org/candlepin/model/ConsumerTest.java
  src/test/java/org/candlepin/service/model/CloudCheckInEventTest.java
Labels: merge after CI

#4942 Update Gradle Wrapper from 8.11 to 8.11.1
  gradle/wrapper/gradle-wrapper.properties
Labels: gradle-wrapper

#4947 [4.5] Revert "CANDLEPIN-938: Reverted explicit content bulk translation"
  src/main/java/org/candlepin/model/ContentCurator.java
  src/main/java/org/candlepin/resource/ContentResource.java
  src/main/java/org/candlepin/resource/OwnerContentResource.java
  src/test/java/org/candlepin/model/ContentCuratorTest.java
Labels: merge after CI

#4948 [4.5] CANDLEPIN-974: Restored page size header when fetching owner pools
  src/main/java/org/candlepin/model/PoolCurator.java
  src/main/java/org/candlepin/resource/OwnerResource.java
Labels: merge after CI

#4951 [4.4] CANDLEPIN-954: Relaxed constraint on null values in ConsumerCloudData
  spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java
  spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Request.java
  spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
  spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
  src/main/java/org/candlepin/model/CloudIdentifierFacts.java
  src/main/java/org/candlepin/model/Consumer.java
  src/main/java/org/candlepin/model/ConsumerCloudData.java
  src/main/java/org/candlepin/resource/ConsumerResource.java
  src/main/java/org/candlepin/util/Util.java
  src/test/java/org/candlepin/model/ConsumerCloudDataTest.java
  src/test/java/org/candlepin/model/ConsumerTest.java
  src/test/java/org/candlepin/service/model/CloudCheckInEventTest.java
Labels: merge after CI
