Repository candlepin/candlepin, pull requests merged in 2024-01, with the labels that each got.

#4463 [M] CANDLEPIN-758: Update/add foreign keys around cp_anonymous_certificates
  src/main/java/org/candlepin/async/tasks/CertificateCleanupJob.java
  src/main/java/org/candlepin/model/AnonymousCloudConsumerCurator.java
  src/main/resources/db/changelog/20240101162555-update-anon-cert-foreign-key.xml
  src/main/resources/db/changelog/changelog-update.xml
  src/test/java/org/candlepin/async/tasks/CertificateCleanupJobTest.java
  src/test/java/org/candlepin/model/AnonymousCloudConsumerCuratorTest.java
  src/test/java/org/candlepin/model/AnonymousCloudConsumerTest.java
Labels: merge after CI

#4455 Migrate to Gradle Version Catalog
  build.gradle
  buildSrc/build.gradle
  buildSrc/settings.gradle
  buildSrc/src/main/groovy/checkstyle-conventions.gradle
  client/build.gradle
  dependencies.gradle
  gradle/libs.versions.toml
  spec-tests/build.gradle
Labels: Needs Second Review, merge after CI

#4122 CANDLEPIN-323: Update exception handling for adapters [M]
  spec-tests/src/test/java/org/candlepin/spec/ExportSpecTest.java
  src/main/java/org/candlepin/async/tasks/CloudAccountOrgSetupJob.java
  src/main/java/org/candlepin/controller/Entitler.java
  src/main/java/org/candlepin/controller/Refresher.java
  src/main/java/org/candlepin/exceptions/mappers/ServiceExceptionMapper.java
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/katello/KatelloUserServiceAdapter.java
  src/main/java/org/candlepin/resource/CloudRegistrationResource.java
  src/main/java/org/candlepin/resource/ConsumerResource.java
  src/main/java/org/candlepin/resource/SubscriptionResource.java
  src/main/java/org/candlepin/resource/UserResource.java
  src/main/java/org/candlepin/resteasy/filter/SecurityHoleAuthorizationFilter.java
  src/main/java/org/candlepin/service/CloudRegistrationAdapter.java
  src/main/java/org/candlepin/service/UserServiceAdapter.java
  src/main/java/org/candlepin/service/exception/ServiceException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/CloudAccountOrgMismatchException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/CloudRegistrationAuthorizationException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/CloudRegistrationMalformedDataException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/CloudRegistrationNotSupportedForOfferingException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/CloudRegistrationServiceException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/CouldNotAcquireCloudAccountLockException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/CouldNotEntitleOrganizationException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/OrgForCloudAccountNotCreatedYetException.java
  src/main/java/org/candlepin/service/exception/cloudregistration/OrgForCloudAccountNotEntitledYetException.java
  src/main/java/org/candlepin/service/exception/entitlementcert/EntitlementCertServiceException.java
  src/main/java/org/candlepin/service/exception/identitycert/IdentityCertServiceException.java
  src/main/java/org/candlepin/service/exception/owner/OwnerServiceException.java
  src/main/java/org/candlepin/service/exception/product/ProductServiceException.java
  src/main/java/org/candlepin/service/exception/subscription/SubscriptionActivationException.java
  src/main/java/org/candlepin/service/exception/subscription/SubscriptionExhaustedTagException.java
  src/main/java/org/candlepin/service/exception/subscription/SubscriptionExpiredTagException.java
  src/main/java/org/candlepin/service/exception/subscription/SubscriptionInvalidTagException.java
  src/main/java/org/candlepin/service/exception/subscription/SubscriptionServiceException.java
  src/main/java/org/candlepin/service/exception/subscription/SubscriptionUnacceptedTermsException.java
  src/main/java/org/candlepin/service/exception/user/UserDisabledException.java
  src/main/java/org/candlepin/service/exception/user/UserInvalidException.java
  src/main/java/org/candlepin/service/exception/user/UserServiceException.java
  src/main/java/org/candlepin/service/exception/user/UserUnacceptedTermsException.java
  src/main/java/org/candlepin/service/exception/user/UserUnauthorizedException.java
  src/main/java/org/candlepin/service/impl/DefaultCloudRegistrationAdapter.java
  src/main/java/org/candlepin/testext/hostedtest/HostedTestCloudRegistrationAdapter.java
  src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
  src/test/java/org/candlepin/auth/TrustedUserAuthTest.java
  src/test/java/org/candlepin/controller/EntitlerTest.java
  src/test/java/org/candlepin/controller/RefresherTest.java
  src/test/java/org/candlepin/exceptions/mappers/ServiceExceptionMapperTest.java
  src/test/java/org/candlepin/hostedtest/HostedTestCloudRegistrationAdapterTest.java
  src/test/java/org/candlepin/resource/AnonymousConsumerResourceCreationTest.java
  src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
  src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
  src/test/java/org/candlepin/resource/ConsumerResourceTest.java
  src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
  src/test/java/org/candlepin/resource/OwnerResourceTest.java
  src/test/java/org/candlepin/resource/RoleResourceTest.java
  src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
  src/test/java/org/candlepin/resource/UserResourceTest.java
  src/test/java/org/candlepin/resteasy/filter/SecurityHoleAuthorizationFilterTest.java
Labels: Needs Second Review

#4506 CANDLEPIN-718: Refactor Distinguished Name construction
  src/main/java/org/candlepin/controller/ContentAccessManager.java
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/model/ProductCertificateCurator.java
  src/main/java/org/candlepin/model/UeberCertificateGenerator.java
  src/main/java/org/candlepin/pki/DistinguishedName.java
  src/main/java/org/candlepin/pki/PKIUtility.java
  src/main/java/org/candlepin/pki/impl/BouncyCastlePKIUtility.java
  src/main/java/org/candlepin/pki/impl/ProviderBasedPKIUtility.java
  src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
  src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java
  src/test/java/org/candlepin/pki/DistinguishedNameTest.java
  src/test/java/org/candlepin/pki/impl/BouncyCastlePKIUtilityTest.java
  src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
  src/test/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapterTest.java
Labels: merge after CI

#4514 CANDLEPIN-778: Add API endpoint for Anonymous Consumer deletion
  api/candlepin-api-spec.yaml
  spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
  src/main/java/org/candlepin/model/AnonymousCloudConsumerCurator.java
  src/main/java/org/candlepin/resource/CloudRegistrationResource.java
  src/test/java/org/candlepin/model/AnonymousCloudConsumerCuratorTest.java
  src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
Labels: merge after CI

#4485 Translations update from Fedora Weblate
  po/as.po
  po/bn_IN.po
  po/de.po
  po/es.po
  po/fr.po
  po/gu.po
  po/hi.po
  po/id.po
  po/it.po
  po/ja.po
  po/kn.po
  po/ko.po
  po/ml.po
  po/mr.po
  po/or.po
  po/pa.po
  po/pt_BR.po
  po/ru.po
  po/si.po
  po/ta.po
  po/te.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: merge after CI
