Repository candlepin/candlepin, pull requests merged in 2024-03, with the labels that each got.

#4593 CANDLEPIN-797: Create product certificate generator
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/model/ProductCertificateCurator.java
  src/main/java/org/candlepin/pki/certs/CertificateCreationException.java
  src/main/java/org/candlepin/pki/certs/ProductCertificateGenerator.java
  src/main/java/org/candlepin/resource/OwnerProductResource.java
  src/main/java/org/candlepin/service/impl/DefaultProductServiceAdapter.java
  src/test/java/org/candlepin/model/ProductCertificateCuratorTest.java
  src/test/java/org/candlepin/pki/certs/ProductCertificateGeneratorTest.java
  src/test/java/org/candlepin/service/impl/DefaultProductServiceAdapterTest.java
Labels: merge after CI

#4592 [F] CANDLEPIN-246: Defined default and max page size for pagination
  src/main/java/org/candlepin/config/ConfigProperties.java
  src/main/java/org/candlepin/config/validation/AbstractConfigurationValidator.java
  src/main/java/org/candlepin/config/validation/ConfigurationValidator.java
  src/main/java/org/candlepin/config/validation/ConfigurationValidatorUtil.java
  src/main/java/org/candlepin/config/validation/IntegerConfigurationValidator.java
  src/main/java/org/candlepin/guice/CandlepinContextListener.java
  src/main/java/org/candlepin/paging/PageRequest.java
  src/main/java/org/candlepin/resource/ConsumerResource.java
  src/main/java/org/candlepin/resource/JobResource.java
  src/main/java/org/candlepin/resource/OwnerResource.java
  src/main/java/org/candlepin/resteasy/filter/PageRequestFilter.java
  src/test/java/org/candlepin/config/TestConfig.java
  src/test/java/org/candlepin/config/validation/AbstractConfigurationValidatorTest.java
  src/test/java/org/candlepin/config/validation/IntegerConfigurationValidatorTest.java
  src/test/java/org/candlepin/resource/ConsumerResourceTest.java
  src/test/java/org/candlepin/resource/OwnerResourceTest.java
  src/test/java/org/candlepin/resteasy/filter/PageRequestFilterTest.java
Labels: merge after CI

#4605 [M] CANDLEPIN-814: Addressed some refresh performance and deadlock issues
  src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
  src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
  src/main/java/org/candlepin/controller/refresher/visitors/NodeProcessor.java
  src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
  src/main/java/org/candlepin/controller/util/ExpectedExceptionRetryWrapper.java
  src/test/java/org/candlepin/controller/refresher/RefreshWorkerTest.java
  src/test/java/org/candlepin/controller/util/ConstraintViolationRetryWrapperTest.java
  src/test/java/org/candlepin/controller/util/ExpectedExceptionRetryWrapperTest.java
Labels: Needs Second Review

#4607 CANDLEPIN-150: Add pagination to getHypervisors endpoint
  api/candlepin-api-spec.yaml
  spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/OwnerClient.java
  spec-tests/src/test/java/org/candlepin/spec/hypervisors/HypervisorCheckInSpecTest.java
  src/main/java/org/candlepin/model/ConsumerCurator.java
  src/main/java/org/candlepin/resource/OwnerResource.java
  src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
  src/test/java/org/candlepin/model/ConsumerCuratorTest.java
  src/test/java/org/candlepin/model/ConsumerTest.java
  src/test/java/org/candlepin/resource/OwnerResourceTest.java
Labels: merge after CI

#4614 CANDLEPIN-816: Added secure method to OwnerCurator for StoreFactory
  src/main/java/org/candlepin/model/OwnerCurator.java
  src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
  src/test/java/org/candlepin/auth/permissions/OwnerCuratorPermissionsTest.java
Labels: merge after CI

#4628 [4.4.1] CANDLEPIN-828: Added owner key in OWNER_CONTENT_ACCESS_MODE event
  src/main/java/org/candlepin/audit/ActivationListener.java
  src/main/java/org/candlepin/audit/Event.java
  src/main/java/org/candlepin/audit/EventAdapterImpl.java
  src/main/java/org/candlepin/audit/EventBuilder.java
  src/main/java/org/candlepin/audit/EventFactory.java
  src/main/java/org/candlepin/audit/LoggingListener.java
  src/main/java/org/candlepin/dto/manifest/v1/SubscriptionDTO.java
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/model/Consumer.java
  src/main/java/org/candlepin/model/Entitlement.java
  src/main/java/org/candlepin/model/Environment.java
  src/main/java/org/candlepin/model/GuestId.java
  src/main/java/org/candlepin/model/Owned.java
  src/main/java/org/candlepin/model/Owner.java
  src/main/java/org/candlepin/model/Pool.java
  src/main/java/org/candlepin/model/activationkeys/ActivationKey.java
  src/main/java/org/candlepin/model/dto/Subscription.java
  src/main/java/org/candlepin/util/ObjectMapperFactory.java
  src/test/java/org/candlepin/TestingModules.java
  src/test/java/org/candlepin/audit/ActivationListenerTest.java
  src/test/java/org/candlepin/audit/DefaultEventMessageReceiverTest.java
  src/test/java/org/candlepin/audit/EventAdapterTest.java
  src/test/java/org/candlepin/audit/EventBuilderTest.java
  src/test/java/org/candlepin/audit/EventFactoryTest.java
  src/test/java/org/candlepin/audit/EventFilterTest.java
  src/test/java/org/candlepin/audit/EventSinkImplTest.java
  src/test/java/org/candlepin/controller/PoolManagerTest.java
  src/test/java/org/candlepin/model/ActivationKeyTest.java
  src/test/java/org/candlepin/model/ConsumerTest.java
  src/test/java/org/candlepin/model/EntitlementTest.java
  src/test/java/org/candlepin/model/EnvironmentTest.java
  src/test/java/org/candlepin/model/GuestIdTest.java
  src/test/java/org/candlepin/model/PoolTest.java
Labels: merge after CI

#4625 CANDLEPIN-800: Create entitlement certificate generator
  src/main/java/org/candlepin/async/tasks/RegenEnvEntitlementCertsJob.java
  src/main/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJob.java
  src/main/java/org/candlepin/bind/HandleCertificatesOp.java
  src/main/java/org/candlepin/controller/ContentManager.java
  src/main/java/org/candlepin/controller/EntitlementCertificateService.java
  src/main/java/org/candlepin/controller/PoolManager.java
  src/main/java/org/candlepin/controller/ProductManager.java
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/model/Entitlement.java
  src/main/java/org/candlepin/model/dto/Content.java
  src/main/java/org/candlepin/model/dto/EntitlementBody.java
  src/main/java/org/candlepin/model/dto/Service.java
  src/main/java/org/candlepin/model/dto/TinySubscription.java
  src/main/java/org/candlepin/pki/OID.java
  src/main/java/org/candlepin/pki/PKIUtility.java
  src/main/java/org/candlepin/pki/certs/AnonymousCertificateGenerator.java
  src/main/java/org/candlepin/pki/certs/EntitlementCertificateGenerator.java
  src/main/java/org/candlepin/pki/certs/EntitlementPayloadGenerator.java
  src/main/java/org/candlepin/pki/certs/SCACertificateGenerator.java
  src/main/java/org/candlepin/pki/certs/UeberCertificateGenerator.java
  src/main/java/org/candlepin/pki/certs/X509StringExtension.java
  src/main/java/org/candlepin/pki/impl/BouncyCastlePKIUtility.java
  src/main/java/org/candlepin/pki/impl/ProviderBasedPKIUtility.java
  src/main/java/org/candlepin/resource/ConsumerResource.java
  src/main/java/org/candlepin/resource/EnvironmentResource.java
  src/main/java/org/candlepin/service/EntitlementCertServiceAdapter.java
  src/main/java/org/candlepin/service/impl/BaseEntitlementCertServiceAdapter.java
  src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
  src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
  src/test/java/org/candlepin/TestingModules.java
  src/test/java/org/candlepin/async/tasks/RegenEnvEntitlementCertsJobTest.java
  src/test/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJobTest.java
  src/test/java/org/candlepin/controller/ContentManagerTest.java
  src/test/java/org/candlepin/controller/EntitlementCertificateServiceTest.java
  src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
  src/test/java/org/candlepin/controller/PoolManagerTest.java
  src/test/java/org/candlepin/controller/ProductManagerTest.java
  src/test/java/org/candlepin/pki/certs/AnonymousCertificateGeneratorTest.java
  src/test/java/org/candlepin/pki/certs/EntitlementCertificateGeneratorTest.java
  src/test/java/org/candlepin/pki/certs/EntitlementPayloadGeneratorTest.java
  src/test/java/org/candlepin/pki/certs/ProductCertificateGeneratorTest.java
  src/test/java/org/candlepin/pki/certs/SCACertificateGeneratorTest.java
  src/test/java/org/candlepin/pki/impl/BouncyCastlePKIUtilityTest.java
  src/test/java/org/candlepin/resource/AnonymousConsumerResourceCreationTest.java
  src/test/java/org/candlepin/resource/ConsumerContentOverrideResourceTest.java
  src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
  src/test/java/org/candlepin/resource/ConsumerResourceTest.java
  src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
  src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
  src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
  src/test/java/org/candlepin/service/impl/stub/StubEntitlementCertServiceAdapter.java
  src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
Labels: merge after CI

#4606 CANDLEPIN-269: Added paging to GET /content endpoint
  api/candlepin-api-spec.yaml
  spec-tests/src/test/java/org/candlepin/spec/ContentResourceSpecTest.java
  src/main/java/org/candlepin/model/ContentCurator.java
  src/main/java/org/candlepin/resource/ContentResource.java
  src/test/java/org/candlepin/model/ContentCuratorTest.java
  src/test/java/org/candlepin/resource/ContentResourceTest.java
Labels: merge after CI

#4602 CANDLEPIN-238: Updated PoolCurator to not use Hibernate Criteria
  src/main/java/org/candlepin/model/AbstractHibernateCurator.java
  src/main/java/org/candlepin/model/PoolCurator.java
  src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
  src/test/java/org/candlepin/controller/PoolServiceFunctionalTest.java
  src/test/java/org/candlepin/model/PoolCuratorTest.java
Labels: merge after CI

#4634 [4.4.1] CANDLEPIN-833: Updated CloudAuthenticationResult validation
  src/main/java/org/candlepin/resource/CloudRegistrationResource.java
  src/main/java/org/candlepin/testext/hostedtest/HostedTestCloudRegistrationAdapter.java
  src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
Labels: merge after CI

#4632 CANDLEPIN-734: Added paging to GET /products endpoint
  api/candlepin-api-spec.yaml
  spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
  src/main/java/org/candlepin/model/ProductCurator.java
  src/main/java/org/candlepin/resource/ProductResource.java
  src/test/java/org/candlepin/model/ProductCuratorTest.java
  src/test/java/org/candlepin/resource/ProductResourceTest.java
Labels: merge after CI

#4636 [M] CANDLEPIN-829: Updated consumer activation key registration testing
  gradle/libs.versions.toml
  spec-tests/build.gradle
  spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
Labels: merge after CI

#4635 [M] CANDLEPIN-827: Removed IllegalStateException when owner does not exist
  src/main/java/org/candlepin/auth/permissions/PermissionFactory.java
  src/test/java/org/candlepin/auth/permissions/PermissionFactoryTest.java
Labels: merge after CI

#4637 Update Gradle Wrapper from 8.6 to 8.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: gradle-wrapper
