Repository candlepin/candlepin, pull requests merged in 2024-02, with the labels that each got.

#4524 CANDLEPIN-698: Change this code to not construct the path from file name entry of an archive
  src/main/java/org/candlepin/sync/Importer.java
Labels: merge after CI

#4527 CANDLEPIN-700: Remove LegacyEncryptedInterceptor
  src/main/java/org/candlepin/config/ConfigProperties.java
  src/main/java/org/candlepin/config/LegacyEncryptedInterceptor.java
  src/main/java/org/candlepin/guice/CandlepinContextListener.java
Labels: merge after CI

#4532 CANDLEPIN-786: Remove XmlTransient tag from eventData
  src/main/java/org/candlepin/audit/Event.java
Labels: merge after CI

#4538 Update Gradle Wrapper from 8.5 to 8.6
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: gradle-wrapper

#4557 [4.1] Make candlepin-4.1-HOTFIX releasable
  candlepin.spec.tmpl
Labels: merge after CI

#4566 CANDLEPIN-718: Extract PEM encoder
  src/main/java/org/candlepin/controller/ContentAccessManager.java
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/model/ProductCertificateCurator.java
  src/main/java/org/candlepin/model/UeberCertificateGenerator.java
  src/main/java/org/candlepin/pki/PKIUtility.java
  src/main/java/org/candlepin/pki/PemEncoder.java
  src/main/java/org/candlepin/pki/PemEncodingException.java
  src/main/java/org/candlepin/pki/impl/BouncyCastlePKIUtility.java
  src/main/java/org/candlepin/pki/impl/BouncyCastlePemEncoder.java
  src/main/java/org/candlepin/pki/impl/ProviderBasedPKIUtility.java
  src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
  src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java
  src/main/java/org/candlepin/sync/Exporter.java
  src/test/java/org/candlepin/TestingModules.java
  src/test/java/org/candlepin/controller/ContentAccessManagerDBTest.java
  src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
  src/test/java/org/candlepin/pki/impl/BouncyCastlePemEncoderTest.java
  src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
  src/test/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapterTest.java
  src/test/java/org/candlepin/service/impl/DefaultProductServiceAdapterTest.java
  src/test/java/org/candlepin/sync/ExporterTest.java
Labels: merge after CI

#4565 [M] CANDLEPIN-801: Added registration only to CloudAuthenticationResult
  client/src/main/java/org/candlepin/resource/HostedTestApi.java
  spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
  src/main/java/org/candlepin/resource/CloudRegistrationResource.java
  src/main/java/org/candlepin/service/model/CloudAuthenticationResult.java
  src/main/java/org/candlepin/testext/hostedtest/HostedTestCloudRegistrationAdapter.java
  src/main/java/org/candlepin/testext/hostedtest/HostedTestResource.java
  src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
Labels: merge after CI

#4568 CANDLEPIN-140: Remove CandlepinQuery from ConsumerResource and ConsumerCurator
  src/main/java/org/candlepin/model/ConsumerCurator.java
  src/main/java/org/candlepin/resource/OwnerResource.java
  src/test/java/org/candlepin/auth/permissions/ConsumerCuratorPermissionsTest.java
  src/test/java/org/candlepin/model/ConsumerCuratorTest.java
  src/test/java/org/candlepin/resource/OwnerResourceTest.java
Labels: merge after CI

#4580 [M] CANDLEPIN-200: Removed CandlepinQuery from ModelTranslator
  src/main/java/org/candlepin/dto/ModelTranslator.java
  src/main/java/org/candlepin/dto/SimpleModelTranslator.java
Labels: merge after CI

#4581 [M] Improved hosted test framework support for large JSON files
  bin/scripts/upstream_data_injector.sh
  src/main/java/org/candlepin/testext/hostedtest/HostedTestResource.java
Labels: merge after CI

#4582 [F] CANDLEPIN-115: Removed CandlepinQuery classes
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/model/AbstractHibernateCurator.java
  src/main/java/org/candlepin/model/CandlepinQuery.java
  src/main/java/org/candlepin/model/CandlepinQueryFactory.java
  src/main/java/org/candlepin/model/DetachedCandlepinQuery.java
  src/main/java/org/candlepin/model/EmptyCandlepinQuery.java
  src/main/java/org/candlepin/model/PermissionBlueprintCurator.java
  src/main/java/org/candlepin/model/TransformedCandlepinQuery.java
  src/main/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptor.java
  src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
  src/test/java/org/candlepin/controller/refresher/RefreshWorkerTest.java
  src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
Labels: Needs Rebase

#4570 CANDLEPIN-796: Create ueber certificate generator
  src/main/java/org/candlepin/guice/CandlepinModule.java
  src/main/java/org/candlepin/pki/certs/UeberCertificateGenerator.java
  src/main/java/org/candlepin/pki/certs/X509CertificateBuilder.java
  src/main/java/org/candlepin/pki/certs/X509CertificateBuilderProvider.java
  src/main/java/org/candlepin/resource/OwnerResource.java
  src/test/java/org/candlepin/async/tasks/UndoImportsJobTest.java
  src/test/java/org/candlepin/model/PoolCuratorTest.java
  src/test/java/org/candlepin/pki/certs/UeberCertificateGeneratorTest.java
  src/test/java/org/candlepin/pki/certs/X509CertificateBuilderTest.java
  src/test/java/org/candlepin/pki/impl/BouncyCastlePemEncoderTest.java
  src/test/java/org/candlepin/resource/OwnerResourceOwnerClaimingTest.java
  src/test/java/org/candlepin/resource/OwnerResourceTest.java
  src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java
Labels: merge after CI
